[package]
name = "test1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.7.6"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "test1"
path = "src/test1.rs"

[[bin]]
name = "test2"
path = "src/test2.rs"

[[bin]]
name = "trait1"
path = "src/trait1.rs"

[[bin]]
name = "get_value"
path = "src/get_value.rs"

[[bin]]
name = "toml_value"
path = "src/toml_value.rs"
